double atan(),	/* arc tangent */
atan2(), /* atan2(a,b) = arc tangent of a/b */
cos(),	/* cosine */
cosh(),	/* hyperbolic cosine */
exp(),	/* exponential */
log(),	/* natural logarithm */
log10(), /* log base 10 */
pow(),	/* pow(x,y) = x**y */
sin(),	/* sine */
sinh(),	/* hyperbolic sine */
sqrt(),	/* square root */
tan(),	/* tangent */
tanh();	/* hyperbolic tangent */
#asm
	GLOBAL	QATAN
	GLOBAL	QATAN2
	GLOBAL	QCOS
	GLOBAL	QCOSH
	GLOBAL	QEXP
	GLOBAL	QLOG
	GLOBAL	QLOG10
	GLOBAL	QPOW
	GLOBAL	QSIN
	GLOBAL	QSINH
	GLOBAL	QSQRT
	GLOBAL	QTAN
	GLOBAL	QTANH
#endasm
